### ISSUE TITLE
Add choices & details to Filters 

### ISSUE THREAD

**Issue by mihow** [RolnickLab/antenna#299]
List views can be filtered from another view, but the filter is mostly read-only and displays just an ID of the related object.

Need a way to query choices for filter drop-downs. Does the OPTIONS request method provide this?

![image](https://github.com/RolnickLab/ami-platform/assets/158175/2f98a691-e26f-4228-85c0-4550ed090315)

**Comment by annavik** [comment]
FIY Andre has some design ready for this, excited to see! I think proper filtering will be a great improvement.

**Comment by annavik** [comment]
@LDalby yes the only way to do filtering atm is to click the "bubble" numbers from other views. For example clicking the "1" here will get you to a list of sessions for this deployment only. I would say this filtering is more a quick hack we did though!

<img width="494" alt="Skärmavbild 2024-06-11 kl  15 38 53" src="https://github.com/RolnickLab/ami-platform/assets/11680517/c705412f-6de6-4ada-98da-8ac3e3fe76fe">
