### ISSUE TITLE
Forbidden error, Jobs fail to start

### ISSUE THREAD

**Issue by mihow** [RolnickLab/antenna#369]
There seems to be a auth issue for the endpoint Forbidden: /api/v2/jobs/[ID]/run/ 

Clicking the Start button shows the ... status dots for one second, then does nothing. No error is displayed.

I think there is a general issue with the CSRF token or the session cookie.

**Comment by mihow** [comment]
@annavik I was able to recreate the issue! It seems like the Session ID cookie does not get cleared when a user is detected as being logged out. Here is a screencast of it happening:
[Screencast from 07-08-2024 02:48:53 PM.webm](https://github.com/RolnickLab/ami-platform/assets/158175/129302f1-8282-4be4-96e6-23c4ba41e049)

**Comment by annavik** [comment]
Hmm, this is very strange! I still have some problems reproducing this. The cookies you have are not present for me to begin with. I wonder if this could be related to admin login messing things up? I mean being logged in on https://api.beluga.insectai.org/admin/? Have you been logged in on this service on localhost?

Here is a short summary of the current FE logic for auth:
- On login, we make a post request to `auth/token/login`. We get a long lived token in response, which we will keep in local storage.
- On logout we first make a post request to BE `auth/token/logout`. Then we clear the auth token from local storage, nothing more. FE is not forcing any cookies to be cleared.
- There are only 2 situations where we will logout the user. First one is when user clicks logout. Second one is if a request to the endpoint `/me` ends up with a 403 response. We call this endpoint every 10 second when the app is active.

Happy to tweak this logic if needed, just want to understand what is going on first :)

**Comment by mihow** [comment]
I think we determined that this is caused if a super admin logs into the Django admin, which creates a CSRF cookie. And then somehow the React frontend tries to use CSRF when making post/put API calls.

**Comment by annavik** [comment]
When visiting the admin UI, cookies are set on the same domain. When we make a backend call, cookies from current domain are passed with the request, which is what is messing things up.

If we want to do something about this, I think the most correct solution would probably happen outside the React app? It would be a bit strange for the React app to have "knowledge" about cookies set by a different app (the admin UI).

If still a problem, I'm not against adding a small hack to fix this though! :)

**Comment by mihow** [comment]
I think the solution to to this is to change the name of the cookie. I will see if I can rename the Django Admin cookie to be `admin_session` instead of `session`
