### ISSUE TITLE
Missing detection count in event response

### ISSUE THREAD

**Issue by annavik** [RolnickLab/antenna#403]
Detection count is set to `null` in backend response, which leads to a missing value for detections in UI:
<img width="659" alt="Skärmavbild 2024-06-10 kl  10 50 50" src="https://github.com/RolnickLab/ami-platform/assets/11680517/e4a85a7d-c492-4e4a-9f2c-48af594a3c43">

For example, I would expect https://api.beluga.insectai.org/api/v2/events/3599/?capture=9415581 to return 38 on field `detections_count` instead of `null`.

**Comment by mihow** [comment]
Closed in #410
