### ISSUE TITLE
Leaflet deployment popup not showing all stats

### ISSUE THREAD

**Issue by LDalby** [RolnickLab/antenna#418]
When clicking a deployment [here](https://app.preview.insectai.org/projects/16), the popup does not include all the stats (missing occurrences and captures)

![image](https://github.com/RolnickLab/ami-platform/assets/2366579/a2cc4d03-dd49-46e1-a400-278acda5acc8)

Build a707661

**Comment by annavik** [comment]
Good catch! 🌟

@mihow I'm missing these numbers from the BE project overview response, would it be possible to add? I could also fetch the deployments separately, but could be nice to avoid this extra request?

**Comment by mihow** [comment]
We decided to remove the missing stats for the time being until the taxa queries are refactored in #490. The page was loading too slowly.
