### ISSUE TITLE
Design & spec out blind labeling feature

### ISSUE THREAD

**Issue by mihow** [RolnickLab/antenna#464]
- What does UKCEH / AMBER project need
- [What do Aditya / Yuyan desire for sampling](https://docs.google.com/document/d/1AMylSfUJqBWLU78Fz9Wi2By383KHM3U3MY-uryTXvvw/edit?usp=sharing)
- New collections feature for crops instead of source images. 
- What does ML need to improve models
- What does research paper need if needed (strictness about bias, etc)
  - Is it okay to use our detector and binary classifier?
- What UI features do we need
- What backend features do we need
- Diagram of the entire feature
- Align on agreements & timelines

MVP: register new ML pipeline with only detector & moth/non-moth classifier

**Comment by joseepoirier** [comment]
Resumed conversation with Jenna. We will meet with them soon, ideally before 26 Sept.

**Comment by mihow** [comment]
I met with Jenna and walked through the platform to see if it could meet their current needs. There are a few things that may need to be done manually by Michael / me on the backend (make a collection for specifically 1-2 deployments). But not a ton other than getting the production environment ready. A new walkthrough video for the annotation project could be very helpful - especially showing how the current filters work. There are a couple easy UI changes that could help.

Notes & timeline here
https://docs.google.com/document/d/1GsrCnxpbDGKmEWktEfQO3F-3ppnrp6dMu8QPV6UQDP0/edit#heading=h.iganhh7knnn

**Comment by mihow** [comment]
We have planned and are working on this feature. We estimate to have all features complete Nov 22 and labeling ready to start at the beginning of December.
