### ISSUE TITLE
Design for filters

### ISSUE THREAD

**Issue by mihow** [RolnickLab/antenna#591]
Design a filters component using the new design system but can work in the existing version of Antenna.

Details are being flushed out here. Specifics to the filters component can be brought into this ticket.
https://docs.google.com/document/d/15HQtKCzTgqDMGeFsDpq4dgP0T72FoYlMvLrR20llLBw/edit

**Comment by annavik** [comment]
Added a similar task here with some more details: https://github.com/RolnickLab/fg-nova/issues/2

Closing this!
