### ISSUE TITLE
Broken image links during local development

### ISSUE THREAD

**Issue by annavik** [RolnickLab/antenna#640]
When running the backend locally, I have some problems with images uploaded from the interface. "Data source images" works fine. Probably some setup step I'm missing.

Example with capture from data source (works fine):
<img width="1728" alt="Screenshot 2024-12-02 at 17 38 40" src="https://github.com/user-attachments/assets/1d35afab-2ff9-4b49-9042-9da08c8607cd">

Example with uploaded capture (broken):
<img width="1728" alt="Screenshot 2024-12-02 at 11 23 51" src="https://github.com/user-attachments/assets/55294ee1-7edc-40b0-b7c6-01b7a1ed2ce8">

**Comment by mihow** [comment]
Ah interesting! Glad you found a fix. However I think there must be a configuration that needs to be updated as well. The manually updated captures are available at minio:9000, but the site is using the django hostname. I will test locally soon.

**Comment by annavik** [comment]
I see! If you find a fix that will better adress the core problem, let's close my PR:) What does your own local workaround look like here?
